__merge__: ../../api/comp_method.yaml

name: scdesign3_poisson
label: scDesign3 (Poisson)
summary: A probabilistic model that unifies the generation and inference for single-cell and spatial omics data
description: |
  scDesign3 offers a probabilistic model that unifies the generation and inference
  for single-cell and spatial omics data. The model's interpretable parameters and
  likelihood enable scDesign3 to generate customized in silico data and unsupervisedly
  assess the goodness-of-fit of inferred cell latent structures (for example, clusters,
  trajectories and spatial locations).
references:
  doi: 10.1038/s41587-023-01772-1
links:
  documentation: https://www.bioconductor.org/packages/release/bioc/html/scDesign3.html
  repository: https://github.com/SONGDONGYUAN1994/scDesign3

arguments:
  - name: "--family"
    type: "string"
    default: poisson
    description: |
      A string or a vector of strings of the marginal distribution. Must be one of 'binomial',
      'poisson', 'nb', 'zip', 'zinb' or 'gaussian', which represent 'poisson distribution',
      'negative binomial distribution', 'zero-inflated poisson distribution',
      'zero-inflated negative binomial distribution', and 'gaussian distribution'
      respectively.
    choices: [binomial, poisson, nb, zip, zinb, gaussian]
  - name: "--usebam"
    type: boolean
    default: false
    description: "Use `bam` for acceleration."

resources:
  - type: r_script
    path: ../scdesign3_nb/script.R

engines:
  - type: docker
    image: openproblems/base_r:1
    setup:
      - type: apt
        packages: [r-bioc-singlecellexperiment, git]
      - type: r
        url:
          - https://cran.r-project.org/src/contrib/Archive/reticulate/reticulate_1.40.0.tar.gz
        github: 
          - SONGDONGYUAN1994/scDesign3

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, midmem, midcpu]
