name: "my_control_method"
namespace: "control_methods"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input"
    info:
      label: "Spatial dataset"
      summary: "An unprocessed spatial dataset as output by a dataset loader."
      description: "This dataset contains raw counts and metadata as output by a dataset\
        \ loader.\n\nThe format of this file is derived from the [CELLxGENE schema\
        \ v4.0.0](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md).\n"
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "integer"
          name: "logcounts"
          description: "Log-transformed counts"
          required: true
        obs:
        - type: "double"
          name: "col"
          description: "Column index of the cell in the spatial grid."
          required: true
        - type: "double"
          name: "row"
          description: "Row index of the cell in the spatial grid."
          required: true
        - type: "double"
          name: "sizeFactor"
          description: "Size factor for the cell."
          required: true
        - type: "integer"
          name: "spatial_cluster"
          description: "Spatial cluster assignment for the cell."
          required: true
        var:
        - type: "string"
          name: "feature_id"
          description: "Unique identifier for the feature, usually a ENSEMBL gene\
            \ id."
          required: false
        - type: "string"
          name: "feature_name"
          description: "A human-readable name for the feature, usually a gene symbol."
          required: true
        obsm:
        - type: "float"
          name: "celltype_proportions"
          description: "Spot-by-celltype matrix of celltype proportions generated\
            \ by CARD."
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - name: "dataset_name"
          type: "string"
          description: "A human-readable name for the dataset."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
          multiple: true
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
          multiple: true
    example:
    - "resources_test/common/mobnew/dataset_sp.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    info:
      label: "Solution"
      summary: "The solution for the test data"
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "integer"
          name: "logcounts"
          description: "Log-transformed counts"
          required: true
        obs:
        - type: "double"
          name: "col"
          description: "Column index of the cell in the spatial grid."
          required: true
        - type: "double"
          name: "row"
          description: "Row index of the cell in the spatial grid."
          required: true
        - type: "double"
          name: "sizeFactor"
          description: "Size factor for the cell."
          required: true
        - type: "integer"
          name: "spatial_cluster"
          description: "Spatial cluster assignment for the cell."
          required: true
        var:
        - type: "string"
          name: "feature_id"
          description: "Unique identifier for the feature, usually a ENSEMBL gene\
            \ id."
          required: false
        - type: "string"
          name: "feature_name"
          description: "A human-readable name for the feature, usually a gene symbol."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - name: "dataset_name"
          type: "string"
          description: "A human-readable name for the dataset."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
          multiple: true
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
          multiple: true
    example:
    - "resources_test/common/mobnew/dataset_sc.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
test_resources:
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
- type: "python_script"
  path: "check_method_config.py"
  is_executable: true
- type: "file"
  path: "library.bib"
info:
  label: "My Control Method"
  summary: "FILL IN: A one sentence summary of this method."
  description: "FILL IN: A (multi-line) description of how this method works.\n"
  preferred_normalization: "log_cp10k"
  type: "control_method"
  type_info:
    label: "Control Method"
    summary: "A control method."
    description: "A control method to predict effects.\n"
status: "enabled"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_spatial_simulators"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "midcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.4"
  namespace_separator: "/"
  entrypoint: []
  cmd: null
build_info:
  config: "src/control_methods/my_control_method/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/control_methods/my_control_method"
  executable: "target/nextflow/control_methods/my_control_method/main.nf"
  viash_version: "0.9.0-RC6"
  git_commit: "56f81c793136dc1de4255aeda6058dec6515c8a5"
  git_remote: "https://github.com/openproblems-bio/task_spatial_simulators"
package_config:
  name: "task_spatial_simulators"
  version: "build_main"
  description: "An OpenProblems benchmark task of spatial simulators.\n"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/task_spatial_simulators"
      dest: "resources_test"
  viash_version: "0.9.0-RC6"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }"
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  - "spatial simulation"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_spatial_simulators"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_spatial_simulators/issues"
