__merge__: ../../api/comp_metric.yaml

name: ks_statistic_spatial

links:
  documentation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html
  repository: https://github.com/scipy/scipy/

info:
  metrics:
    - name: ks_statistic_transition_matrix
      label: Transition matrix
      summary: KS Statistic of the transition matrix.
      description: |
        The Kolmogorov-Smirnov statistic comparing the transition matrix of the real dataset versus the simulated dataset. The transition matrix elucidates the interrelationships among spatial clusters in each space. Each element in the matrix signifies the transition probability from one spatial cluster to another, thereby mapping the dynamic interplay of spatial clusters.
      references:
        doi: 10.1201/9780429485572
      min: -Inf
      max: +Inf
      maximize: false
    - name: ks_statistic_central_score
      label: Centralized score
      summary: Ks Statistic of the centralized score matrix.
      description: |
        The Kolmogorov-Smirnov statistic comparing the centralized score matrix of the real dataset versus the simulated dataset. The centralized score matrix is a vector of the group degree centrality (inter-cluster connectivity), average clustering coefficient (propensity for a spot within a spatial cluster to be connected to spots in another cluster), and the group closeness centrality (relative proximity or accessibility of one cluster to all spots in another). 
      references:
        doi: 10.1201/9780429485572
      min: -Inf
      max: +Inf
      maximize: false
    - name: ks_statistic_enrichment
      label: Neighborhood enrichment
      summary: Ks Statistic of the neighborhood enrichment.
      description: |
        The Kolmogorov-Smirnov statistic comparing the neighborhood enrichment matrices of the real dataset versus the simulated dataset. The neighborhood enrichment matrix quantifies the enrichment observed between each pair of spatial clusters. It serves to systematically assess the interaction between different clusters within a spatial context, providing insights into the relative connectivity between various spatial clusters.
      references:
        doi: 10.1201/9780429485572
      min: -Inf
      max: +Inf
      maximize: false

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages:
          - numpy
          - scikit-learn
          - squidpy 
          - scipy

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
