__merge__: ../../api/comp_metric.yaml

name: ks_statistic_gene_cell

info:
  metrics:
    - name: ks_statistic_frac_zero_genes
      label: Fraction of zeros in genes
      summary: KS Statistic of the fraction of zeroes in the genes
      description: |
        The Kolmogorov-Smirnov statistic comparing the fraction of zeros in the
        genes of the real counts versus the fraction of zeros in the genes of
        the predicted counts.
      # reference: doi?
      # documentation_url: https://url.to/the/documentation
      # repository_url: https://github.com/organisation/repository
      min: -Inf
      max: +Inf
      maximize: false
    - name: ks_statistic_frac_zero_cells
      label: Fraction of zeros in cells
      summary: KS Statistic of the fraction of zeroes in the cells
      description: |
        The Kolmogorov-Smirnov statistic comparing the fraction of zeros in the
        cells of the real counts versus the fraction of zeros in the cells of
        the predicted counts.
      # reference: doi?
      # documentation_url: https://url.to/the/documentation
      # repository_url:
      min: -Inf
      max: +Inf
      maximize: false

resources:
  - type: r_script
    path: script.R

engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_images/r:1.1.0
    setup:
      - type: apt
        packages: 
          - git
          - r-bioc-edger
          - r-cran-ks
          - r-cran-resample
          - r-cran-reshape2

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
