name: "ks_statistic_spatial"
namespace: "metrics"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input_spatial_dataset"
    info:
      label: "Spatial dataset"
      summary: "An unprocessed spatial dataset as output by a dataset loader."
      description: "This dataset contains raw counts and metadata as output by a dataset\
        \ loader.\n\nThe format of this file is derived from the [CELLxGENE schema\
        \ v4.0.0](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md).\n"
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "integer"
          name: "logcounts"
          description: "Log-transformed counts"
          required: true
        obs:
        - type: "double"
          name: "col"
          description: "Column index of the cell in the spatial grid."
          required: true
        - type: "double"
          name: "row"
          description: "Row index of the cell in the spatial grid."
          required: true
        - type: "double"
          name: "sizeFactor"
          description: "Size factor for the cell."
          required: true
        - type: "integer"
          name: "spatial_cluster"
          description: "Spatial cluster assignment for the cell."
          required: true
        var:
        - type: "string"
          name: "feature_id"
          description: "Unique identifier for the feature, usually a ENSEMBL gene\
            \ id."
          required: false
        - type: "string"
          name: "feature_name"
          description: "A human-readable name for the feature, usually a gene symbol."
          required: true
        obsm:
        - type: "float"
          name: "celltype_proportions"
          description: "Spot-by-celltype matrix of celltype proportions generated\
            \ by CARD."
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - name: "dataset_name"
          type: "string"
          description: "A human-readable name for the dataset."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
          multiple: true
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
          multiple: true
    example:
    - "resources_test/datasets/MOBNEW/dataset_sp.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input_singlecell_dataset"
    info:
      label: "Single-cell dataset"
      summary: "An unprocessed single-cell dataset as output by a dataset loader."
      description: "This dataset contains raw counts and metadata as output by a dataset\
        \ loader.\n\nThe format of this file is derived from the [CELLxGENE schema\
        \ v4.0.0](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md).\n"
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        obs:
        - type: "string"
          name: "cell_type"
          description: "Classification of the cell type based on its characteristics\
            \ and function within the tissue or organism."
          required: false
        - type: "string"
          name: "donor_id"
          description: "Identifier for the donor from whom the cell sample is obtained."
          required: false
        var:
        - type: "string"
          name: "feature_id"
          description: "Unique identifier for the feature, usually a ENSEMBL gene\
            \ id."
          required: false
        - type: "string"
          name: "feature_name"
          description: "A human-readable name for the feature, usually a gene symbol."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - name: "dataset_name"
          type: "string"
          description: "A human-readable name for the dataset."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
          multiple: true
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
          multiple: true
    example:
    - "resources_test/datasets/MOBNEW/dataset_sc.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input_simulated_dataset"
    info:
      label: "Solution"
      summary: "The solution for the test data"
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        obs:
        - type: "double"
          name: "col"
          description: "Column index of the cell in the spatial grid."
          required: true
        - type: "double"
          name: "row"
          description: "Row index of the cell in the spatial grid."
          required: true
        var:
        - type: "string"
          name: "feature_id"
          description: "Unique identifier for the feature, usually a ENSEMBL gene\
            \ id."
          required: false
        - type: "string"
          name: "feature_name"
          description: "A human-readable name for the feature, usually a gene symbol."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset. This is different from\
            \ the `obs.dataset_id` field, which is the identifier for the dataset\
            \ from which the cell data is derived."
          required: true
        - name: "dataset_name"
          type: "string"
          description: "A human-readable name for the dataset."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
          multiple: true
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
          multiple: true
        - name: "method_id"
          type: "string"
          description: "A unique identifier for the method used to generate the dataset."
          required: true
    example:
    - "resources_test/datasets/MOBNEW/simulated_dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    info:
      label: "Score"
      summary: "File indicating the score of a metric."
      file_type: "h5ad"
      slots:
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
        - type: "string"
          name: "metric_ids"
          description: "One or more unique metric identifiers"
          multiple: true
          required: true
        - type: "double"
          name: "metric_values"
          description: "The metric values obtained for the given prediction. Must\
            \ be of same length as 'metric_ids'."
          multiple: true
          required: true
    example:
    - "resources/score.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
test_resources:
- type: "python_script"
  path: "check_metric_config.py"
  is_executable: true
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
- type: "file"
  path: "library.bib"
- type: "file"
  path: "resources_test/datasets"
  dest: "resources_test/datasets"
info:
  metrics:
  - name: "ks_statistic_transition_matrix"
    label: "Transition matrix"
    summary: "KS Statistic of the transition matrix."
    description: "The Kolmogorov-Smirnov statistic comparing the transition matrix\
      \ of the real dataset versus the simulated dataset. The transition matrix elucidates\
      \ the interrelationships among spatial clusters in each space. Each element\
      \ in the matrix signifies the transition probability from one spatial cluster\
      \ to another, thereby mapping the dynamic interplay of spatial clusters.\n"
    documentation_url: "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html"
    repository_url: "https://github.com/scipy/scipy/"
    min: "-Inf"
    max: "+Inf"
    maximize: false
  - name: "ks_statistic_central_score"
    label: "Centralized score"
    summary: "Ks Statistic of the centralized score matrix."
    description: "The Kolmogorov-Smirnov statistic comparing the centralized score\
      \ matrix of the real dataset versus the simulated dataset. The centralized score\
      \ matrix is a vector of the group degree centrality (inter-cluster connectivity),\
      \ average clustering coefficient (propensity for a spot within a spatial cluster\
      \ to be connected to spots in another cluster), and the group closeness centrality\
      \ (relative proximity or accessibility of one cluster to all spots in another).\
      \ \n"
    documentation_url: "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html"
    repository_url: "https://github.com/scipy/scipy/"
    min: "-Inf"
    max: "+Inf"
    maximize: false
  - name: "ks_statistic_enrichment"
    label: "Neighborhood enrichment"
    summary: "Ks Statistic of the neighborhood enrichment."
    description: "The Kolmogorov-Smirnov statistic comparing the neighborhood enrichment\
      \ matrices of the real dataset versus the simulated dataset. The neighborhood\
      \ enrichment matrix quantifies the enrichment observed between each pair of\
      \ spatial clusters. It serves to systematically assess the interaction between\
      \ different clusters within a spatial context, providing insights into the relative\
      \ connectivity between various spatial clusters.\n"
    documentation_url: "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html"
    repository_url: "https://github.com/scipy/scipy/"
    min: "-Inf"
    max: "+Inf"
    maximize: false
  type: "metric"
  type_info:
    label: "Metric"
    summary: "A metric."
    description: "A metric for evaluating method predictions.\n"
status: "enabled"
repositories:
- type: "github"
  name: "openproblems_v2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_spatial_simulators"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "midcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_images/python:1.1.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    packages:
    - "numpy"
    - "scikit-learn"
    - "squidpy"
    - "scipy"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/metrics/ks_statistic_spatial/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/metrics/ks_statistic_spatial"
  executable: "target/nextflow/metrics/ks_statistic_spatial/main.nf"
  viash_version: "0.9.0-RC7"
  git_commit: "d2b627258609eda200a06f7c46aa315298dd87eb"
  git_remote: "https://github.com/openproblems-bio/task_spatial_simulators"
package_config:
  name: "task_spatial_simulators"
  version: "build_main"
  label: "Spatial Simulators"
  summary: "Assessing the quality of spatial transcriptomics simulators"
  description: "Computational methods for spatially resolved transcriptomics (SRT)\
    \ are frequently developed \nand assessed through data simulation. The effectiveness\
    \ of these evaluations relies on the \nsimulation methods' ability to accurately\
    \ reflect experimental data. However, a systematic \nevaluation framework for\
    \ spatial simulators is lacking. Here, we present SpatialSimBench, \na comprehensive\
    \ evaluation framework that assesses 13 simulation methods using 10 distinct \n\
    STR datasets.\n\nThe research goal of this benchmark is to systematically evaluate\
    \ and compare the\nperformance of various simulation methods for spatial transcriptomics\
    \ (ST) data.\nIt aims to address the lack of a comprehensive evaluation framework\
    \ for spatial simulators\nand explore the feasibility of leveraging existing single-cell\
    \ simulators for ST data.\nThe experimental setup involves collecting public spatial\
    \ transcriptomics datasets and\ncorresponding scRNA-seq datasets.\nThe spatial\
    \ and scRNA-seq datasets can originate from different study but should consist\n\
    of similar cell types from similar tissues.\n"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/task_spatial_simulators"
      dest: "resources_test"
  repositories:
  - type: "github"
    name: "openproblems_v2"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
  viash_version: "0.9.0-RC7"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n.runners[.type == \"nextflow\"].config.script := \"process.errorStrategy\
    \ = 'ignore'\""
  authors:
  - name: "Xiaoqi Liang"
    roles:
    - "author"
    - "maintainer"
    info:
      orcid: "0009-0004-9625-1441"
      github: "littlecabiria"
  - name: "Yue Cao"
    roles:
    - "author"
    info:
      orcid: "0000-0002-2356-4031"
      github: "ycao6928"
  - name: "Jean Yang"
    roles:
    - "author"
    info:
      orcid: "0000-0002-5271-2603"
      github: "jeany21"
  - name: "Robrecht Cannoodt"
    roles:
    - "contributor"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Sai Nirmayi Yasa"
    roles:
    - "contributor"
    info:
      github: "sainirmayi"
      orcid: "0009-0003-6319-9803"
  keywords:
  - "single-cell"
  - "spatial transcriptomics"
  - "in-silico"
  - "spatial simulation"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    doi:
    - "10.1101/2024.05.29.596418"
  links:
    repository: "https://github.com/openproblems-bio/task_spatial_simulators"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_spatial_simulators/issues"
