name: convert
namespace: process_datasets
description: Transform the figshare rds into an HDF5-backed AnnData file.

argument_groups:
  - name: Inputs
    arguments:
      - type: file
        name: --input_sc
        description: Raw single-cell dataset
        example: resources_test/spatialsimbench_mobnew/MOBNEW_sc.rds
        required: true
      - type: file
        name: --input_sp
        description: Raw spatial dataset
        example: resources_test/spatialsimbench_mobnew/MOBNEW.rds
        required: true

  - name: Outputs
    arguments:
      - name: --output_sc
        __merge__: ../../api/file_dataset_sc.yaml
        direction: output
        required: true     
      - name: --output_sp
        __merge__: ../../api/file_dataset_sp.yaml
        direction: output
        required: true

  - name: Dataset metadata
    description: Metadata about the dataset, used for documentation and provenance.
    arguments:
      - type: string
        name: --dataset_id
        description: A unique identifier for the dataset.
        required: true
        info: 
          test_default: mobnew
      - type: string
        name: --dataset_name
        description: A human-readable name for the dataset.
        required: true
        info: 
          test_default: MOBNEW
      - type: string
        name: --dataset_url
        description: Link to the original source of the dataset.
        required: false
      - type: string
        name: --dataset_reference
        description: A doi for the dataset.
        example: 10.1234/s1234-5678-9012-3
        required: false
        multiple: true
      - type: string
        name: --dataset_summary
        description: Short description of the dataset.
        required: true
        info: 
          test_default: MOBNEW
      - type: string
        name: --dataset_description
        description: Long description of the dataset.
        required: true
        info: 
          test_default: MOBNEW
      - type: string
        name: --dataset_organism
        description: Organism from which the dataset was derived.
        required: true
      - type: string
        name: --dataset_assay_spatial
        description: "Assay used for spatial data."
        required: true
        info:
          test_default: Visium
      - type: string
        name: --dataset_assay_singlecell
        description: "Assay used for single-cell data."
        required: true
        info:
          test_default: Chromium

resources:
  - type: r_script
    path: script.R

test_resources:
  - path: /resources_test/spatialsimbench_mobnew
    dest: resources_test/spatialsimbench_mobnew
  - type: python_script
    path: /common/component_tests/run_and_check_output.py

engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        bioc: [SingleCellExperiment]

runners:
  - type: executable
  - type: nextflow