name: sc_features
namespace: process_datasets
description: Add scFeatures in adata
argument_groups:
  - name: Inputs
    arguments:
      - name: --input_sp
        description: Raw spatial dataset
        required: true
        __merge__: /src/api/file_dataset_sp.yaml

  - name: Outputs
    arguments:
      - type: file
        name: --output_sp
        description: Processed spatial dataset
        example: dataset_sp.h5ad
        direction: output
        required: true

resources:
  - type: r_script
    path: script.R

test_resources:
  - path: /resources_test/spatialsimbench_mobnew
    dest: resources_test/spatialsimbench_mobnew
  - type: python_script
    path: /common/component_tests/run_and_check_output.py

engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        github: [SydneyBioX/scFeatures]

runners:
  - type: executable
  - type: nextflow