__merge__: ../../api/comp_method.yaml

name: srtsim
label: SRTsim
summary: An SRT-specific simulator for scalable, reproducible, and realistic SRT simulations.
description: |
  A key benefit of srtsim is its ability to maintain location-wise and gene-wise SRT count properties and 
  preserve spatial expression patterns, enabling evaluation of SRT method performance using synthetic data. 
references:
  doi: 10.1186/s13059-023-02879-z

info:
  documentation_url: https://xzhoulab.github.io/SRTsim
  repository_url: https://github.com/xzhoulab/srtsim

resources:
  - type: r_script
    path: script.R

engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        cran: SRTsim

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
