__merge__: ../../api/comp_method.yaml

name: srtsim

info:
  label: srtsim
  summary: An SRT-specific simulator for scalable, reproducible, and realistic SRT simulations.
  description: |
    A key benefit of srtsim is its ability to maintain location-wise and gene-wise SRT count properties and 
    preserve spatial expression patterns, enabling evaluation of SRT method performance using synthetic data. 
  reference: 110.1186/s13059-023-02879-z
  documentation_url: https://xzhoulab.github.io/srtsim/
  repository_url: https://github.com/xzhoulab/srtsim

resources:
  - type: r_script
    path: script.R

engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_images/r:1.1.0
    setup:
      - type: r
        bioc: srtsim

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
