__merge__: /src/api/comp_process_datasets.yaml
name: "process_datasets"
namespace: "workflows"
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf
dependencies:
  - name: process_datasets/convert
  - name: process_datasets/sc_features
  - name: process_datasets/precompute_downstream
runners:
  - type: nextflow
