__merge__: ../../api/comp_method.yaml

name: symsim
label: symsim
summary: Simulating multiple faceted variability in single cell RNA sequencing
description: |
  SymSim is a simulator for modeling single-cell RNA-Seq data, accounting for three primary sources of variation: intrinsic transcription noise, extrinsic variation from different cell states, 
  and technical variation from measurement noise and bias.
references:
  doi: 10.1038/s41467-019-10500-w
links:
  documentation: https://github.com/YosefLab/SymSim/blob/master/vignettes/SymSimTutorial.Rmd
  repository: https://github.com/YosefLab/SymSim

resources:
  - type: r_script
    path: script.R

engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        bioc: SingleCellExperiment
        github: YosefLab/SymSim

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
