__merge__: ../../api/comp_control_method.yaml

name: negative_normal
label: negative_normal
summary: A negative control which generates normal distributed data.
description: |
  This control method generates normal distributed data as a negative control.
  The mean and the sd are defined by the mean and sd of the input data.

resources:
  - type: r_script
    path: script.R

engines:
  - type: docker
    image: openproblems/base_r:1.0.0

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]